# frozen_string_literal: true

require "rake/testtask"
require "shellwords"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.pattern = "test/**/*_test.rb"
  t.verbose = true
end

task default: :test

namespace :features do
  desc "Run all devcontainer feature tests via npm"
  task :test do
    sh "npm test"
  end

  desc "Run autogenerated tests for one feature (FEATURE=ruby IMAGE=ubuntu:latest)"
  task :autogenerated do
    feature = ENV["FEATURE"]
    abort "Set FEATURE, for example: rake features:autogenerated FEATURE=ruby" if feature.nil? || feature.empty?

    image = ENV.fetch("IMAGE", "ubuntu:latest")
    sh "cd features && npx devcontainer features test --skip-scenarios -f #{Shellwords.escape(feature)} -i #{Shellwords.escape(image)} ."
  end

  desc "Run scenario tests for one feature (FEATURE=ruby)"
  task :scenarios do
    feature = ENV["FEATURE"]
    abort "Set FEATURE, for example: rake features:scenarios FEATURE=ruby" if feature.nil? || feature.empty?

    sh "cd features && npx devcontainer features test -f #{Shellwords.escape(feature)} --skip-autogenerated --skip-duplicated ."
  end
end
