name: Build and Publish New Ruby Versions

on:
  workflow_dispatch:
    inputs:
      ruby_versions:
        type: string
        required: true
        description: List of ruby versions to build. Should be an array ["3.3.1","3.2.4"]
      image_versions:
        type: string
        required: true
        description: List of image versions to build. Should be an array ["ruby-1.1.0"]

jobs:
  publish:
    name: Publish Images
    uses: ./.github/workflows/publish-images-reusable.yaml
    with:
      ruby_versions_json: ${{ github.event.inputs.ruby_versions }}
      image_versions_json: ${{ github.event.inputs.image_versions }}
      repository_owner: ${{ github.repository_owner }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
